### ISSUE TITLE
Can't view my fund or portfolio!

### ISSUE THREAD

**Issue by plutoegg** [melonproject/portal#238]
Connected via parity, went through disclaimer and created my fund 'EFX Mega Super Fund'. Transaction successfully mined, but then nothing showed up on the UI, and clicking on Create fund and Create portfolio had no effect :(

- Will Harborne

**Comment by plutoegg** [comment]
Fund creation hash showing an out of gas issue / possibly throw

https://kovan.etherscan.io/tx/0xa87fbdb5083be099545236b98c61aaae02f17a4039380c8695207258b0dbd8e7

**Comment by travs** [comment]
Looks like you don't have any ETH at [your address](https://kovan.etherscan.io/address/0x6817323a99e6f5afca61b2c1e1e996af72d0422e).

I will send you some shortly and you can try again :)

**Comment by travs** [comment]
It might be that parity provides a lower gas limit by default, since the gas limit in the tx you linked seems quite low.
We can fix this by adding a `{gas: someLargeNumber}` parameter to web3 transaction calls. In this case, it would be [this function I believe](https://github.com/melonproject/portal/blob/6832ab90c648c1ec54344dd771a8dc6bf3835936/imports/ui/components/portal/portalNew.js#L67).

**Comment by jennazenk** [comment]
Hey Will! Thanks for reporting this issue! As Travis said, might be gas limit issue! You can try to change your gas limit or try to access the portal w Metamask until we deploy a fix for that. We will fix it by adding the gas parameter to the functions calls to the contracts :)
