### ISSUE TITLE
“Visitor View” isn’t work for me on mobile (android - chrome) or PC (firefox and chrome).

### ISSUE THREAD

**Issue by thehighfiveghost** [melonproject/portal#247]
“Visitor View” isn’t work for me on mobile (android - chrome) or PC (firefox and chrome).

**Comment by schmidsi** [comment]
Can you make a screenshot & give exact OS/Browser version?

What do you mean by "isn't working"? Similar like this: #239? Or a bluescreen?

**Comment by retotrinkler** [comment]
![screenshot from 2017-06-21 17-55-21](https://user-images.githubusercontent.com/13721565/27393927-d5d96a2e-56aa-11e7-9285-b1efa70f64e7.png)

instead of the database image there should be the portfolio list - visitor view essentially is a way to look at the portfolio list and their performance/contents (fund page) without needing to be connected
