### ISSUE TITLE
Initial pointers and questions

### ISSUE THREAD

**Issue by oliver-fwe** [melonproject/portal#287]
Hi Melon Team,
First of all great work on the portal, looks really slick and after having initial connection issues it was super fast to set up a fund! I have been having some fun playing around and trading/managing a fund and here are some initial questions and pointers:
1. When setting up a fund and initially investing in the fund I had to accept 3 transactions, maybe worth having a small pop up explaining what is happening in the back ground. As for a traditional asset manager new to the crypto space they would want to know the work flow, especially given they are paying in Gas for the transactions to go through.
2. Consider adding a leverage feature, and allowing portfolio marginning
3. The Bid Ask price is the wrong way round for this asset pair. It appears it spontaneously appears in the correct way but this is maybe something to look into.
![bidask](https://user-images.githubusercontent.com/29064794/27595322-46e2271c-5b54-11e7-879f-034672bcd11a.JPG)
4. Is it possible to not set up a fund but to invest in other funds?
5. In the Fund Holdings table, it would be helpful to see a line by line breakdown of the performance for the fund. For example, intra day performance for each asset.
6. Other things maybe to consider are displaying, average execution prices for entry and exit, realised and unrealised P&Ls.
7. For one trade I sent it was 'Sending' for a few minutes then just got lost and didn't execute. There should be some kind of audit trail for every trade sent, so if the trade didn't get sent/executed I should be notified.

Great work on the v0.1 and keep up the good work!

**Comment by schmidsi** [comment]
Hi Oliver,

Thanks for your great feedback! This really helps us building the portal, so it is the best tool for you.

1. We are working on this. Best would be to have just one transaction that sets everything up. But if this is not possible, the idea with a clear status indicator like "Step 1 of 3: Creating your vault" would be great for user experience. New Issue: #289
2. As far as I understand, marginning and leveraging is not in the scope of the portal. That said, it would be possible in the future that some third party integrating this functionality independently as Melon-modules.
3. There are possibly some small inconsistencies with our liquidity provider, but we are looking into it.
4. Technically, it's already kind of possible by the smart contracts. But there is no use case for this yet. But surely, this will come. I created a new issue here: #290
5. Great idea: #291
6. Great idea: #292
7. There are still some issues with Metamask and the communication to the blockchain in general. We are on the bleeding edge here, but we'll find ways around it: #293. Thanks for pointing out.

I'm closing this issue since I broke it down in more actionable issues.
