### ISSUE TITLE
bid/ask inconsistency

### ISSUE THREAD

**Issue by jennazenk** [melonproject/portal#295]

**Comment by travs** [comment]
Will check this out in `daemon` today, and see if it's a problem there.

**Comment by retotrinkler** [comment]
could be due to the build in randomness https://github.com/melonproject/daemon/blob/6e5961c664a3552b5684a3a5ef1ed25e4815739d/imports/api/orders.js#L237

bid/ask w negative spread (due to randomness) was intended to be a simple starter to build a arbitrage trading strategy

but debatable if it makes sense to have this for once competitions start - i'd be in favor to give incentive to start building alg trading bots etc :)
