### ISSUE TITLE
Crossed order book

### ISSUE THREAD

**Issue by bangers89** [melonproject/portal#319]
I have noticed a crossing order book (bid > or = ask)
<img width="1186" alt="screen shot 2017-07-10 at 17 16 28" src="https://user-images.githubusercontent.com/4448049/28028621-0cb74950-6595-11e7-9ce7-7dcd94cee9c8.png">

**Comment by jennazenk** [comment]
Hello @bangers89 , thank you for your feedback.
Our exchange doesn't have a matching algorithm, it is expected behavior that negative bid/ask spread can occur. Ultimately, we would like to incentivize people to start building algorithm trading bots and pave the way for potential arbitrage strategies!
